#!/bin/bash

FILES=$(exec git diff-index --check --cached HEAD -- | sed '/^[+-]/d' | awk -F ":" '{print $1}' | uniq )

if [ ! -n "$FILES" ]; then
  exit 0
fi

for FILE in $FILES; do
  echo "'$FILE' has trailing whitespace"
done
echo "Commit aborted"
exit 1
