#!/bin/bash

# Make sure none of the files are large
function check-for-big-files() {
  # Init
  BIG=200
  echo "* Check for big files: du \$file > $BIG"

  for file in $(git diff --name-only HEAD^); do
    # Exit early - continue the loop if the file is not big
    test "$(du "$file" | awk '{print $1}')" -gt "$BIG" || continue

    # Deal with big files
    echo -n "Are you happy with committing $file? It is big. [y/N]? "
    read -n 1 ANSWER
    echo
    if [[ "$ANSWER" =~ [yY] ]]; then
      continue
    else
      echo "This file is ~/Desktop/source/hawkeye/.git/hooks/pre-commit"
      git diff --name-only | du -sh
      exit 1
    fi
  done
}

# Read user input, assign stdin to keyboard
exec < /dev/tty
echo "Pre-commit hook"
check-for-big-files
exec <&-

