# Use 'C-s' to read in this file's settings. And 'C-e' to edit it
bind-key C-s source-file "$XDG_CONFIG_HOME/tmux/tmux.conf" \; display-message "Sourced tmux.conf"
bind-key C-e new-window \; send-keys "\$EDITOR $XDG_CONFIG_HOME/tmux/tmux.conf" Enter

# Source all the other config files
source-file ~/.config/tmux/plugin/*.conf

# Source remote plugins if we are remote and if any exist
if-shell 'test -n "$SSH_CLIENT" && test -d ~/.config/tmux/plugin/remote' 'source-file ~/.config/tmux/plugin/remote/*.conf'

# Source local (machine-specific) plugins if any exist
if-shell 'test -d ~/.local/share/tmux/plugin' 'source-file ~/.local/share/tmux/plugin/*.conf'

# List of plugins
# set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'AriSweedler-at/tmux-typhon'

# Override TPM plugins with local dev copies
run 'for d in ~/.local/share/tmux/local-plugins/*/; do [ -d "$d" ] || continue; n="$(basename "$d")"; t="$TMUX_PLUGIN_MANAGER_PATH/$n"; [ -L "$t" ] || rm -rf "$t"; ln -sfn "$d" "$t"; done'

# Initialize TMUX plugin manager
# Keep this line at the very bottom of tmux.conf
# Keep this in sync with 'TMUX_PLUGIN_MANAGER_ROOT' in
#   ~/.config/zsh/plugins/tmux.zsh
run "~/.local/share/tmux/tpm/tpm"

# Auto-install missing plugins
run '~/.local/share/tmux/tpm/bin/install_plugins >/dev/null 2>&1'
