################################ status line ############################### {{{
# Single variable to set the styling for a given statusline mode.
typhon_sm="#{?client_prefix,\
#[fg=${typhon_fg_active}]#[bg=${typhon_bg_active}],\
#[fg=${typhon_fg_default}]#[bg=${typhon_bg_default}]}"

# And another variable that allows me to display state
typhon_keys_off="#{?#{==:#(tmux show-option -qv key-table),OFF_keytable},#[bg=${typhon_bg_off}] OFF ,}"
################################### left ################################### {{{
# Customize status line message and style. Google `man tmux "FORMATS"`
# (http://man7.org/linux/man-pages/man1/tmux.1.html#FORMATS)
# There are style directives `#[]`
# and there ternary statements: `#(?boolean,option1,option2}`
set-option -g status-left-length 80
set-option -g status-left "\
${typhon_sm}\
 Session: #S \
#{?pane_synchronized,#[bg=${typhon_bg_sync}] (S) ,}\
#{?window_zoomed_flag,#[bg=${typhon_bg_zoom}] (Z) ,}\
#{?#{==:#{pane_mode},"copy-mode"},#[bg=${typhon_bg_copy}] COPY ,}\
#{?selection_present,#[bg=${typhon_bg_select}] SELECTION ,}\
$typhon_modes\
$typhon_keys_off\
"
############################################################################ }}}
################################## center ################################## {{{
# Put the window list in the center
set-option -g status-justify centre

# Set the style for windows in the window list
set-option -g window-status-format '#{?client_prefix,#[underscore],} #I: #W '
set-option -g window-status-current-format '#{?client_prefix,#[underscore],} #I: #W :) '

# highlight the active and last windows
set-option -g status-style fg=${typhon_fg},bg=${typhon_bg}
set-option -g window-status-current-style bg=${typhon_bg_highlight}
set-option -g window-status-last-style bg=${typhon_bg_highlight_2}
############################################################################ }}}
################################### right ################################## {{{
# The syntax for nested if statements is whacky! This looks okay, though. I'm
# pretending its an "if-elseif-else" block. We use this early-exiting if-elif
# check to choose a color {{{
set-option -g status-right-length 80
set-option -g status-right "\
${typhon_sm}\
$typhon_keys_off\
$typhon_modes\
#{?window_zoomed_flag,#[bg=${typhon_bg_zoom}] (Z) ,}\
#{?pane_synchronized,#[bg=${typhon_bg_sync}] (S) ,}\
#{?selection_present,#[bg=${typhon_bg_select}],\
#{?pane_in_mode,#[bg=${typhon_bg_copy}],\
#{?client_prefix,#[bg=${typhon_bg_active}],\
#[bg=${typhon_bg_default}]}}} \
#h | %a %b %d [UTC #($HOME/.config/bin/tmux-utc-date)] [%Z %I:%M%p] \
"
############################################################################ }}}
############################################################################ }}}
