-- local movement_keys = {Y = {x = -10, y = -10},
--                        K = {x = 0,   y = -10},
--                        U = {x = 10,  y = -10},
--                        H = {x = -10, y = 0},
--                        L = {x = 10,  y = 0},
--                        B = {x = -10, y = 10},
--                        J = {x = 0,   y = 10},
--                        N = {x = 10,  y = 10}}
--
-- movement_keys.foreach(key, function(k,v) -- TODO idk how to marry these
-- local axis_move = {-10, 0, 10}
-- for _,x in ipairs(axis_move) do
--   for _,y in ipairs(axis_move) do
--     local next_key = movement_keys.next
--     print(string.format("Hello x=%s and y=%s", x, y))
--   end
-- end
--
-- local function makeMovementBinding(key, movement)
--   local cb = function()
--     local win = hs.window.focusedWindow()
--     local f = win:frame()
--
--     f.x = f.x + movement.x
--     f.y = f.y + movement.y
--     win:setFrame(f)
--   end
--   hs.hotkey.bind({"cmd", "alt", "ctrl"}, key, cb)
-- end
--
-- for key, movement in pairs(movement_keys) do
--   makeMovementBinding(key, movement)
-- end
--
