#!/usr/bin/env bash
# brewfile::merge: both tiers verbatim, in order, no dedupe; a missing local tier is marked.
set -u
# shellcheck source=lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

world_new
world_use_fixture drift
G="${BREW_SHIM_FIXTURE}/Brewfile.global"
L="${BREW_SHIM_FIXTURE}/Brewfile.local.dup"
run_id="$(TZ=UTC date -r "${NEW_MACHINE_NOW}" '+%Y%m%dT%H%M%S')"

zfn brew.zsh brewfile::merge "${FIX}/merged" "${G}" "${L}"
assert_eq "merge exits 0" 0 "${RC}"
{
  printf '%s\n' "# generated by new-machine run_id=${run_id}; edit the tier files, not this"
  printf '%s\n' "# ── tier: global  ${G}"
  cat "${G}"
  printf '%s\n' "# ── tier: local   ${L}"
  cat "${L}"
} > "${FIX}/expected"
if cmp -s "${FIX}/expected" "${FIX}/merged"; then pass "header + both bodies verbatim, in order"
else fail "header + both bodies verbatim, in order" "$(diff "${FIX}/expected" "${FIX}/merged")"; fi
assert_eq "duplicates preserved" 2 "$(grep -c '^brew "jq"$' "${FIX}/merged")"

zfn brew.zsh brewfile::merge "${FIX}/merged2" "${G}" "${FIX}/no-such-local"
assert_eq "merge without local exits 0" 0 "${RC}"
{
  printf '%s\n' "# generated by new-machine run_id=${run_id}; edit the tier files, not this"
  printf '%s\n' "# ── tier: global  ${G}"
  cat "${G}"
  printf '%s\n' "# ── tier: local   ${FIX}/no-such-local"
  printf '%s\n' "# (absent)"
} > "${FIX}/expected2"
if cmp -s "${FIX}/expected2" "${FIX}/merged2"; then pass "absent local tier is marked"
else fail "absent local tier is marked" "$(diff "${FIX}/expected2" "${FIX}/merged2")"; fi

zfn brew.zsh brewfile::merge "${FIX}/merged3" "${FIX}/no-such-global"
if (( RC != 0 )); then pass "missing global Brewfile is an error"; else fail "missing global Brewfile is an error" "rc=0"; fi

report
